docs_dir: docs/
repo_name: 'tyson-swetnam/ecosystem-energy-fields'
repo_url: 'https://github.com/tyson-swetnam/ecosystem-energy-fields'

site_name: 'Ecosystems as Energy Fields'
site_description: 'Documentation for associated research.'
site_author: 'Tyson L Swetnam'
site_url: 'https://tyson-swetnam.github.io/ecosystem-energy-fields'

edit_uri: edit/main/docs

# Copyright
copyright: 'Copyright &copy; 2023 Tyson Lee Swetnam'

# Navigation Page

nav:
  - 'Home': 
    - 'Home': index.md 
    - 'Background': background.md
    - 'Data': data.md
    - 'Methods': methods.md
    - 'Results': results.md
    - 'Conclusions': conclusions.md
    
# JavaScript for Intercom Widget
extra_javascript:
  - javascripts/intercom-learning.js
  
# Set theme to `readthedocs`
# must also set Action to use `@nomaterial` branch instead of `@master` for material
theme:
  name: material
# setting features for the navigation tab
  features:
    - navigation.instant
      #- navigation.expand
    - navigation.tracking
    - navigation.sections
    - navigation.indexes
    - toc.follow
  # Default values, taken from mkdocs_theme.yml
  language: en
  palette: 
    - scheme: default
      primary: teal
      accent: blue
      toggle:
        icon: material/brightness-3
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: orange 
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
  font:
    text: Roboto
    code: Regular
    icon:
    logo: material/pine-tree-fire

# Options
extra:
  social:
    - icon: fontawesome/brands/orcid
      link: https://orcid.org/0000-0002-6639-7181
    - icon: simple/googlescholar  
      link: https://scholar.google.com/citations?user=nanIeAYAAAAJ&hl=en
    - icon: fontawesome/brands/github
      link: https://github.com/tyson-swetnam/
    - icon: fontawesome/brands/mastodon
      link: https://fosstodon.org/@tswetnam  
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/tswetnam
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/tyson-swetnam
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/tswetnam
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UC5xPt9KZHccC0ehMNEkINzQ
  analytics:
    provider: google
    property: G-NYETZFD8DN
  
extra_css:
  - stylesheets/extra.css

# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
    - search
    - mkdocstrings
    - git-revision-date
    - mkdocs-jupyter:
          include_source: True
          ignore_h1_titles: True
